// Self-host the two UI faces (both OFL). Asks Google's CSS API with a modern
// Chrome UA so it answers with woff2 + unicode-range subsets, keeps the
// `latin` block of each face, downloads it and writes src/ui/fonts.css.
// Run once: node scripts/fetch-fonts.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Archivo:wght@500;700;900&display=swap';
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';
const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text();
const blocks = [...css.matchAll(/\/\*\s*(\w[\w-]*)\s*\*\/\s*@font-face\s*{([^}]*)}/g)]
  .map((m) => ({ subset: m[1], body: m[2] }))
  .filter((b) => b.subset === 'latin');
if (!blocks.length) { console.error('no latin @font-face blocks in the response:\n' + css.slice(0, 600)); process.exit(1); }
fs.mkdirSync(path.join(root, 'public/fonts'), { recursive: true });
const faces = [];
for (const b of blocks) {
  const family = b.body.match(/font-family:\s*'([^']+)'/)[1];
  const weight = b.body.match(/font-weight:\s*(\d+)/)[1];
  const url = b.body.match(/url\(([^)]+\.woff2)\)/)[1];
  const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${weight}.woff2`;
  const bytes = Buffer.from(await (await fetch(url)).arrayBuffer());
  fs.writeFileSync(path.join(root, 'public/fonts', file), bytes);
  faces.push({ family, weight, file, size: bytes.length });
  console.log(`${file} ${(bytes.length / 1024).toFixed(0)} KB`);
}
const out = ['/* Self-hosted UI faces (Permanent Marker + Archivo, both OFL). Generated by scripts/fetch-fonts.mjs — do not edit by hand. */',
  ...faces.map((f) => `@font-face { font-family: '${f.family}'; font-style: normal; font-weight: ${f.weight}; font-display: swap; src: url('/fonts/${f.file}') format('woff2'); }`)];
fs.writeFileSync(path.join(root, 'src/ui/fonts.css'), out.join('\n') + '\n');
console.log(`wrote src/ui/fonts.css with ${faces.length} faces`);
